name: task_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.2
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  flutter_slidable: ^1.2.0
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
